# Generated by Django 6.0 on 2026-01-14 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_destination'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='maps_url',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='rating',
        ),
        migrations.AddField(
            model_name='destination',
            name='category',
            field=models.CharField(default='default', max_length=100),
        ),
    ]
